Categories:
  - Sports & Health
License: GPL-3.0-only
WebSite: https://quiet-strength-recovery.netlify.app/
SourceCode: https://github.com/jockmcc/quiet-strength-recovery
IssueTracker: https://github.com/jockmcc/quiet-strength-recovery/issues
RepoType: git
Repo: https://github.com/jockmcc/quiet-strength-recovery.git

Builds:
  - versionName: '1.7'
    versionCode: 2
    commit: HEAD
    subdir: android-release
    gradle:
      - yes

CurrentVersion: '1.7'
CurrentVersionCode: 2
